### ISSUE TITLE
stuck and timeout at get_trafficmanager in leaderboard_evaluator.py

### ISSUE THREAD

**Issue by pastapeter** [opendilab/LMDrive#58]
Hi, I'm facing issue when starting, i got segmentation Fault when Setting up the Agent.
```
========= Preparing RouteScenario_3 (repetition 0) =========
> Setting up the agent
Fatal Python error: Segmentation fault

Thread 0x00007ffbd8f67700 (most recent call first):
  File "/home/dohyun/miniconda3/envs/lmdrive/lib/python3.8/threading.py", line 306 in wait
  File "/home/dohyun/miniconda3/envs/lmdrive/lib/python3.8/threading.py", line 558 in wait
  File "/home/dohyun/miniconda3/envs/lmdrive/lib/python3.8/threading.py", line 1252 in run
  File "/home/dohyun/miniconda3/envs/lmdrive/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/home/dohyun/miniconda3/envs/lmdrive/lib/python3.8/threading.py", line 890 in _bootstrap

Current thread 0x00007ffbf9be2280 (most recent call first):
  File "/home/dohyun/LMDrive/leaderboard/team_code/lmdriver_agent.py", line 80 in __init__
  File "/home/dohyun/LMDrive/leaderboard/team_code/lmdriver_agent.py", line 175 in setup
  File "/home/dohyun/LMDrive/leaderboard/leaderboard/autoagents/autonomous_agent.py", line 45 in __init__
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 276 in _load_and_run_scenario
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 422 in run
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 487 in main
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 496 in <module>
./leaderboard/scripts/run_evaluation.sh: line 45: 295043 Segmentation fault      (core dumped) python3 -u ${LEADERBOARD_ROOT}/leaderboard/leaderboard_evaluator.py --scenarios=${SCENARIOS} --routes=${ROUTES} --repetitions=${REPETITIONS} --track=${CHALLENGE_TRACK_CODENAME} --checkpoint=${CHECKPOINT_ENDPOINT} --agent=${TEAM_AGENT} --agent-config=${TEAM_CONFIG} --debug=${DEBUG_CHALLENGE} --record=${RECORD_PATH} --resume=${RESUME} --port=${PORT} --trafficManagerPort=${TM_PORT}
```

How can i solve it?
Carla library is 0.9.15

**Comment by pastapeter** [comment]
I just deleted the self._display  in lmdrive_agent.py this issue has been solved

**Comment by yk112233** [comment]
hi, @pastapeter . I encountered the same problem, I delete the codes including self._display in the lmdriver_agent.py, however, I still cannot solve it, is there anything wrong in my operation, eagerly waiting for your reply.

**Comment by pastapeter** [comment]
Sorry. After that, I faced other issue which I cannot remember right now..

if you solve the issue, can you comment here??

**Comment by yk112233** [comment]
Thanks for your reply. I'm trying to solve the issue. If you have some advice, please let me know.
